import type { Metadata } from "next";
import { GeistMono, GeistSans } from "geist/font";
import { hasLocale } from "next-intl";
import { getMessages, getTimeZone, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import "../globals.css";
import { routing } from "@/i18n/routing";
import { Providers } from "../providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	setRequestLocale(locale);

	const messages = await getMessages();
	const timeZone = await getTimeZone();

	return (
		<html lang={locale}>
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
				<Providers locale={locale} messages={messages} timeZone={timeZone}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
